MarvelMovies.Web/Models/MoviesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MarvelMovies.Web.Models
{
    public class MoviesViewModel
    {
        public Movie EditedMovie { get; set; }
        public Movie RemovedMovie { get; set; }
        public List<Movie> ListOfMovies { get; set; }

    }
}

MarvelMovies.Web/Controllers/MoviesController.cs
using AutoMapper;
using MarvelMovies.Data;
using MarvelMovies.Logic;
using MarvelMovies.Repository;
using MarvelMovies.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MarvelMovies.Web.Controllers
{
    public class MoviesController : Controller
    {
        ILogic logic;
        IMapper mapper;
        MoviesViewModel vm;

        public MoviesController()
        {
            vm = new MoviesViewModel();

            logic = new MarvelMoviesLogicTool();
            mapper = MapperFactory.CreateMapper();

            vm.EditedMovie = new Movie();
            var moviesVar = logic.ListMovies();

            vm.ListOfMovies = mapper.Map<IEnumerable<Data.MOVy>, List<Models.Movie>>(moviesVar);
        }


        private Movie GetMovie(int id)
        {
            MOVy movie = logic.ListMovies().FirstOrDefault(x => x.MOVID == id);

            return mapper.Map<MOVy, Movie>(movie, new Movie());
        }



        // GET: Movies
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("MoviesIndex", vm);
        }

        // GET: Movies/Details/5
        public ActionResult Details(int id)
        {
            return View("MovieDetails", GetMovie(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";

            if (logic.DeleteMovie(id)) TempData["editResult"] = "Delete OK";

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedMovie = GetMovie(id);
            return View("MoviesIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Movie movie, string editAction)
        {
            if (ModelState.IsValid && movie != null)
            {
                var editOrAddEntity = mapper.Map<Movie, MOVy>(movie);

                if (editAction == "Edit")
                {
                    TempData["editResult"] = "Edit OK";

                    if (!logic.UpdateMovie(editOrAddEntity))
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                else
                {
                    TempData["editResult"] = "Add new OK";

                    ((MarvelMoviesLogicTool)logic).CreateMovie(editOrAddEntity, movie.CollectionName);
                }

                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedMovie = movie;

                return View("MoviesIndex", vm);
            }
        }
    }
}

MarvelMovies.Web/Views/Movies/MovieDetails.cshtml
@model MarvelMovies.Web.Models.Movie
@{
    ViewBag.Title = "MovieDetails";
}

<h2>Datasheet of one car</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>The ID of the Movie</td>
        <td>@Model.MOVID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MOVIE_NAME)</td>
        <td>@Html.DisplayFor(m => m.MOVIE_NAME)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.TITLE)</td>
        <td>@Html.DisplayFor(m => m.TITLE)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.RELEASE_YEAR)</td>
        <td>@Html.DisplayFor(m => m.RELEASE_YEAR)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.RUNTIME)</td>
        <td>@Html.DisplayFor(m => m.RUNTIME)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.TOMATOMETER)</td>
        <td>@Html.DisplayFor(m => m.TOMATOMETER)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.AUDIENCE_SCORE)</td>
        <td>@Html.DisplayFor(m => m.AUDIENCE_SCORE)</td>
    </tr>
</table>

MarvelMovies.Web/Views/Movies/MovieEdit.cshtml
@model MarvelMovies.Web.Models.Movie

<h2>Edit one Movie</h2>

@using (Html.BeginForm("Edit", "Movies"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.MOVID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.MOVIE_NAME)</div>
    <div class="editor-field">@Html.EditorFor(m => m.MOVIE_NAME)</div>

    <div class="editor-label">@Html.LabelFor(m => m.TITLE)</div>
    <div class="editor-field">@Html.EditorFor(m => m.TITLE)</div>

    <div class="editor-label">@Html.LabelFor(m => m.RELEASE_YEAR)</div>
    <div class="editor-field">@Html.EditorFor(m => m.RELEASE_YEAR)</div>

    <div class="editor-label">@Html.LabelFor(m => m.RUNTIME)</div>
    <div class="editor-field">@Html.EditorFor(m => m.RUNTIME)</div>

    <div class="editor-label">@Html.LabelFor(m => m.TOMATOMETER)</div>
    <div class="editor-field">@Html.EditorFor(m => m.TOMATOMETER)</div>

    <div class="editor-label">@Html.LabelFor(m => m.AUDIENCE_SCORE)</div>
    <div class="editor-field">@Html.EditorFor(m => m.AUDIENCE_SCORE)</div>

    <div class="editor-label">@Html.LabelFor(m => m.AUDIENCE_SCORE)</div>
    <div class="editor-field">@Html.EditorFor(m => m.AUDIENCE_SCORE)</div>

    if (ViewData["editAction"] == "AddNew")
    {
        <div class="editor-label">@Html.LabelFor(m => m.CollectionName)</div>
        <div class="editor-field">@Html.EditorFor(m => m.CollectionName)</div>
    }

    <input type="submit" value="SAVE" />
}

MarvelMovies.Web/Views/Movies/MovieList.cshtml
@model IEnumerable<MarvelMovies.Web.Models.Movie>

<h2>List of Movies</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().MOVIE_NAME)</th>
            <th>@Html.DisplayNameFor(m => m.First().TITLE)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.MOVIE_NAME)</td>
            <td>@Html.DisplayFor(m => item.TITLE)</td>
            <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.MOVID })</td>
            <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.MOVID })</td>
            <td>@Html.ActionLink("[Edit]", "Edit", new { id = item.MOVID })</td>
        </tr>
        }
    </table>
}

MarvelMovies.Web/Views/Movies/MoviesIndex.cshtml
@model MarvelMovies.Web.Models.MoviesViewModel

@{
    ViewBag.Title = "Movies Index";
}

<h2>Movies Index</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("MovieEdit", Model.EditedMovie)

@Html.Partial("MovieList", Model.ListOfMovies)